export const ROUTES = {
  LANDING: '/',
  DASHBOARD: '/dashboard',
  STUDENT_HACKATHON_HISTORY: '/student/hackathons',
  STUDENT_TEAM: '/student/team',
  STUDENT_MATCHMAKING: '/student/matchmaking',
  STUDENT_RESULTS: '/student/results',
  STUDENT_ROUND_RESULTS: '/student/results/:roundId',
  HACKATHONS: '/hackathons',
  HACKATHON_CREATE: '/hackathons/create',
  HACKATHON_SETUP: '/hackathons/:hackathonId/setup',
  TRACKS: '/hackathons/:hackathonId/tracks',
  ROUNDS: '/hackathons/:hackathonId/rounds',
  ROUND_RANKING_PREVIEW: '/hackathons/:hackathonId/rounds/:roundId/ranking-preview',
  ROUND_RESULTS: '/hackathons/:hackathonId/rounds/:roundId/results',
  PUBLIC_ROUND_SCOREBOARD: '/rounds/:roundId/scoreboard',
  CRITERIA: '/hackathons/:hackathonId/criteria/:roundId',
  GLOBAL_TEAMS: '/teams',
  REVIEW_VALIDATE: '/hackathons/:hackathonId/review',
  LOGIN: '/login',
  REGISTER: '/register',
  GITHUB_CALLBACK: '/auth/github/callback',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  ONBOARDING: '/onboarding',
  CHANGE_PASSWORD: '/change-password',
  USER_APPROVAL: '/admin/users',
  TEMP_JUDGES: '/admin/temp-judges',
  PROFILE: '/profile',
  JUDGE_DASHBOARD: '/judge/dashboard',               // Trang Dashboard tổng quan
  JUDGE_SCORING: '/judging/:assignmentId/scoring',   // Phòng chấm thi trực tiếp
  JUDGE_CRITERIA: '/judge/criteria',
  MENTOR_SUPPORT: '/mentor/support',
  MENTOR_ROUNDS: '/mentor/rounds',
  MENTOR_HISTORY: '/mentor/history',
  STUDENT_ANNUAL_AWARDS: '/student/annual-awards',
  STUDENT_SUBMIT: '/student/submit',
  STUDENT_EVENTS: '/student/events',
  COORDINATOR_LATE_SUBMISSIONS: '/coordinator/late-submissions',
  COORDINATOR_KIT_DESK: '/coordinator/kit-desk',
  PRESENTATION_QUEUE: '/presentation/queue',
  COORDINATOR_ANALYTICS: '/coordinator/analytics',
  COORDINATOR_FINAL_CONFIG: '/coordinator/final-config',
  HACKATHON_PRIZES_PRINT: '/hackathons/:hackathonId/prizes/print',
  HACKATHON_PRIZES_CERTIFICATES: '/hackathons/:hackathonId/prizes/certificates',
  PUBLIC_HALL_OF_FAME: '/hall-of-fame',
  PUBLIC_ARTICLE: '/news/:slug',
};

