export const HACKATHON_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  FINISHED: 'FINISHED',
};

export const TRACK_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
};

export const ROUND_TIEBREAK_RULE = {
  PENALTY_SCORE: 'PENALTY_SCORE',
  SUBMISSION_TIME: 'SUBMISSION_TIME',
  COORDINATOR_DECISION: 'COORDINATOR_DECISION',
};
