# Port chạy động trên Render
server.port=${PORT:8080}

# Cấu hình kết nối MySQL sử dụng biến môi trường trên Render
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tắt hiển thị câu lệnh SQL ở môi trường production để tối ưu hiệu năng
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Giữ nguyên cấu hình schema.sql để tự động tạo bảng nếu chưa có
spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.sql.init.schema-locations=classpath:schema.sql

# Cấu hình xử lý việc Railway tự động ngắt kết nối
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1

spring.cache.type=redis
spring.data.redis.url=${REDIS_URL}


# Cấu hình pool kết nối
spring.data.redis.lettuce.pool.max-active=7
spring.data.redis.lettuce.pool.max-idle=7
spring.data.redis.lettuce.pool.min-idle=2