export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/auth/login',
    REGISTER: '/api/v1/auth/register',
    LOGOUT: '/api/v1/auth/logout',
    LOGOUT_ALL: '/api/v1/auth/logout-all',
    REFRESH: '/api/v1/auth/refresh',
    FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
    RESET_PASSWORD: '/api/v1/auth/reset-password',
    VERIFY_EMAIL: '/api/v1/auth/verify-email',
    RESEND_VERIFICATION: '/api/v1/auth/resend-verification',
    OAUTH_GOOGLE_LOGIN: '/api/v1/auth/oauth/google',
    OAUTH_GITHUB_LOGIN_CODE: '/api/v1/auth/oauth/github/code',
    OAUTH_GOOGLE_LINK: '/api/v1/auth/oauth/google/link',
    OAUTH_GITHUB_LINK_CODE: '/api/v1/auth/oauth/github/link/code',
    OAUTH_GOOGLE_UNLINK: '/api/v1/auth/oauth/google/unlink',
    OAUTH_GITHUB_UNLINK: '/api/v1/auth/oauth/github/unlink',
    CHANGE_PASSWORD: '/api/v1/auth/change-password',
  },
  HACKATHONS: {
    BASE: '/api/v1/hackathons',
    DETAIL: (id) => `/api/v1/hackathons/${id}`,
    READINESS: (id) => `/api/v1/hackathons/${id}/readiness`,
    STATUS: (id) => `/api/v1/hackathons/${id}/status`,
    BANNER: (id) => `/api/v1/hackathons/${id}/banner`,
    ROUNDS: (hackathonId) => `/api/v1/hackathons/${hackathonId}/rounds`,
    TRACKS: (hackathonId) => `/api/v1/hackathons/${hackathonId}/tracks`,
    EVENTS: (hackathonId) => `/api/v1/hackathons/${hackathonId}/events`,
    LOTTERY: (hackathonId) => `/api/v1/hackathons/${hackathonId}/lottery`,
    CLOSE_REGISTRATION_EARLY: (id) => `/api/v1/hackathons/${id}/close-registration-early`,
    COMPETITION_SCHEDULE_PREVIEW: (id) => `/api/v1/hackathons/${id}/competition-schedule/preview`,
    COMPETITION_SCHEDULE_ADJUST: (id) => `/api/v1/hackathons/${id}/competition-schedule/adjust`,
    REGISTRATION_EXTENSION_PREVIEW: (id) => `/api/v1/hackathons/${id}/registration/extension/preview`,
    REGISTRATION_EXTENSION: (id) => `/api/v1/hackathons/${id}/registration/extension`,
    // query assumeCloseRegToday=true khi preview trong modal đóng ĐK sớm

    CLONE: (id) => `/api/v1/hackathons/${id}/clone`,
    KIT_ITEMS: (hackathonId) => `/api/v1/hackathons/${hackathonId}/kit-items`,
    KIT_BUNDLES: (hackathonId) => `/api/v1/hackathons/${hackathonId}/kit-bundles`,
    KIT_RECIPIENTS: (hackathonId) => `/api/v1/hackathons/${hackathonId}/kits/recipients`,
    KIT_ISSUE: (hackathonId) => `/api/v1/hackathons/${hackathonId}/kits/issue`,
    KIT_ISSUE_BUNDLE: (hackathonId) => `/api/v1/hackathons/${hackathonId}/kits/issue-bundle`,
    KIT_RECONCILIATION: (hackathonId) => `/api/v1/hackathons/${hackathonId}/kits/reconciliation`,
    KIT_CLONE_SOURCES: (hackathonId) => `/api/v1/hackathons/${hackathonId}/kits/clone-sources`,
    KIT_CLONE: (hackathonId) => `/api/v1/hackathons/${hackathonId}/kits/clone`,
  },
  KITS: {
    ITEM_DETAIL: (id) => `/api/v1/kit-items/${id}`,
    ITEM_STOCK: (id) => `/api/v1/kit-items/${id}/stock`,
    ITEM_STOCKS: (id) => `/api/v1/kit-items/${id}/stocks`,
    BUNDLE_DETAIL: (id) => `/api/v1/kit-bundles/${id}`,
    ALLOCATION_REVOKE: (id) => `/api/v1/kit-allocations/${id}/revoke`,
  },
  ME_KITS: {
    SHIRT_SIZES: '/api/v1/me/shirt-sizes',
    SHIRT_SIZE: '/api/v1/me/shirt-size',
    HACKATHON_SHIRT_SIZE: (hackathonId) => `/api/v1/me/hackathons/${hackathonId}/shirt-size`,
  },
  TEAMS: {
    BASE: '/api/v1/teams',
    BULK_APPROVE: '/api/v1/teams/bulk-approve',
    DETAIL: (teamId) => `/api/v1/teams/${teamId}`,
    STATUS: (teamId) => `/api/v1/teams/${teamId}/status`,
    APPROVE: (teamId) => `/api/v1/teams/${teamId}/approve`,
    TRANSFER_LEADER: (teamId) => `/api/v1/teams/${teamId}/transfer-leader`,
    CONFIRM_FORMATION: (teamId) => `/api/v1/teams/${teamId}/confirm-formation`,
    
    INVITE_MEMBER: (teamId) => `/api/v1/teams/${teamId}/members/invite`,
    MEMBER_DETAIL: (teamId, userId) => `/api/v1/teams/${teamId}/members/${userId}`,
    
    // FR-13B-R: Đổi track (Đã gộp cả UPDATE_TRACK và TRACK để không bị lỗi)
    UPDATE_TRACK: (teamId, roundId) => `/api/v1/teams/${teamId}/rounds/${roundId}/track`,
    TRACK: (teamId, roundId) => `/api/v1/teams/${teamId}/rounds/${roundId}/track`, 
    
    // FR-13C: Quản lý Mentor theo vòng
    MENTOR: (teamId, roundId) => `/api/v1/teams/${teamId}/rounds/${roundId}/mentor`,
    MENTOR_HISTORY: (teamId) => `/api/v1/teams/${teamId}/mentors`,

    ORPHANS: (hackathonId) => `/api/v1/teams/hackathons/${hackathonId}/orphans`,
    INCOMPLETE_TEAMS: (hackathonId) => `/api/v1/teams/hackathons/${hackathonId}/incomplete-teams`,
    MATCHMAKING: (hackathonId) => `/api/v1/teams/hackathons/${hackathonId}/matchmaking`,
    ADMIN_CREATE: '/api/v1/teams/admin-create',
    ADMIN_ADD_MEMBER: (teamId) => `/api/v1/teams/${teamId}/admin-add-member`,
    ADMIN_MERGE: (teamId) => `/api/v1/teams/${teamId}/admin-merge`,
    JOURNEY: (teamId) => `/api/v1/teams/${teamId}/journey`,
  },
  STUDENT_HACKATHONS: {
    BROWSE: '/api/v1/me/hackathons/browse',
    REGISTER: (id) => `/api/v1/me/hackathons/${id}/register`,
  },
  STUDENT_PORTAL: {
    CREATE_TEAM: '/api/v1/me/teams',
    HISTORY: '/api/v1/me/history',
    ANNUAL_AWARDS: '/api/v1/me/annual-awards',
    TRACK_SELECT: (trackId) => `/api/v1/me/tracks/${trackId}/select`,
    SELECTABLE_TRACKS: (hackathonId) => `/api/v1/me/hackathons/${hackathonId}/selectable-tracks`,
    RELOTTERY_TRACK: (teamId, roundId) =>
      `/api/v1/me/teams/${teamId}/rounds/${roundId}/track`,
  },
  MENTOR_PORTAL: {
    TEAM_ASSIGNMENTS: '/api/v1/me/mentor-team-assignments',
    TRACK_ASSIGNMENTS: '/api/v1/me/mentor-track-assignments',
    PRESENTATION_SLOT: (teamId) =>
      `/api/v1/me/mentor-team-assignments/${teamId}/presentation-slot`,
    ROUND_SCHEDULE: (roundId) => `/api/v1/me/mentor/rounds/${roundId}/schedule`,
    HACKATHON_RANKINGS: (hackathonId) =>
      `/api/v1/me/mentor/hackathons/${hackathonId}/rankings`,
    HISTORY: '/api/v1/me/mentor-history',
  },
  ROUNDS: {
    BASE: '/api/v1/rounds',
    DETAIL: (id) => `/api/v1/rounds/${id}`,
    TRACKS: (roundId) => `/api/v1/rounds/${roundId}/tracks`,
    CRITERIA: (roundId) => `/api/v1/rounds/${roundId}/criteria`,
    CRITERIA_CLONE: (roundId) => `/api/v1/rounds/${roundId}/criteria/clone`,
    ACTIVATE: (id) => `/api/v1/rounds/${id}/activate`,
    RELEASE_PROBLEM: (id) => `/api/v1/rounds/${id}/release-problem`,
    CLOSE_SUBMISSION_EARLY: (id) => `/api/v1/rounds/${id}/close-submission-early`,
    PROBLEM_STATEMENT: (id) => `/api/v1/rounds/${id}/problem-statement`,
    SCORING_PROGRESS: (id) => `/api/v1/rounds/${id}/scoring-progress`,
    PUBLISH: (id) => `/api/v1/rounds/${id}/publish`,
    ADVANCE: (id) => `/api/v1/rounds/${id}/advance`,
  },
  TRACKS: {
    BASE: '/api/v1/tracks',
    DETAIL: (id) => `/api/v1/tracks/${id}`,
    PROBLEM_STATEMENT: (id) => `/api/v1/tracks/${id}/problem-statement`,
    RELEASE_PROBLEM: (id) => `/api/v1/tracks/${id}/release-problem`,
    CRITERIA: (trackId) => `/api/v1/tracks/${trackId}/criteria`,
    CRITERIA_CLONE: (trackId) => `/api/v1/tracks/${trackId}/criteria/clone`,
  },
  CRITERIA: {
    DETAIL: (id) => `/api/v1/criteria/${id}`,
    TEMPLATES: '/api/v1/criteria-templates',
    TEMPLATE_DETAIL: (id) => `/api/v1/criteria-templates/${id}`,
    APPLY_TEMPLATE_TO_TRACK: (trackId, templateId) =>
      `/api/v1/tracks/${trackId}/criteria/templates/${templateId}/apply`,
    APPLY_TEMPLATE_TO_ROUND: (roundId, templateId) =>
      `/api/v1/rounds/${roundId}/criteria/templates/${templateId}/apply`,
  },
  EVENTS: {
    DETAIL: (id) => `/api/v1/events/${id}`,
    BUFFET_MENU: (id) => `/api/v1/events/${id}/buffet-menu`,
  },
  USERS: {
    ME: '/api/v1/users/me',
    ME_STUDENT_CARD: '/api/v1/users/me/student-card',
    LOOKUP: '/api/v1/users/lookup',
    LOOKUP_COORDINATOR: '/api/v1/users/lookup/coordinator',
    STATUS: (userId) => `/api/v1/users/${userId}/status`,
    LIST: '/api/v1/users',
    DETAIL: (userId) => `/api/v1/users/${userId}`,
    TEMP_JUDGES: '/api/v1/users/temp-judges',
    RESEND_INVITATION: (invitationId) => `/api/v1/invitations/${invitationId}/resend`,
    REVOKE_INVITATION: (invitationId) => `/api/v1/invitations/${invitationId}/revoke`,
    JUDGE_ROUND_ASSIGNMENTS: (judgeId) => `/api/v1/users/${judgeId}/round-assignments`,
    MENTOR_TRACK_ASSIGNMENTS: (mentorId) => `/api/v1/users/${mentorId}/track-assignments`,
    PATCH: (userId) => `/api/v1/users/${userId}`,
  },
  EXPORT_JOBS: {
    LIST_BY_HACKATHON: (hackathonId) => `/api/v1/hackathons/${hackathonId}/export-jobs`,
    DETAIL: (id) => `/api/v1/export-jobs/${id}`,
    DOWNLOAD: (id) => `/api/v1/export-jobs/${id}/download`,
  },
  JUDGE: {
    SUBMISSIONS: '/api/v1/me/judge/submissions',
  },
  SUBMISSIONS: {
    BASE: '/api/v1/submissions',
    DETAIL: (id) => `/api/v1/submissions/${id}`,
    SLIDE: (id) => `/api/v1/submissions/${id}/slide`,
    GITHUB: (id) => `/api/v1/submissions/${id}/github`,
  },
  PRESENTATION: {
    QUEUE: '/api/v1/presentation/queue',
    QUEUE_SHUFFLE: '/api/v1/presentation/queue/shuffle',
    QUEUE_NEXT: '/api/v1/presentation/queue/next',
    TIMER_START: '/api/v1/presentation/timer/start',
    TIMER_PAUSE: '/api/v1/presentation/timer/pause',
    TIMER_RESUME: '/api/v1/presentation/timer/resume',
    TIMER_QA: '/api/v1/presentation/timer/qa',
    TIMER_END: '/api/v1/presentation/timer/end',
    TIMER_RESET: '/api/v1/presentation/timer/reset',
    DURATION: '/api/v1/presentation/duration',
    TRACK_CONTROLLER: (trackId) => `/api/v1/presentation/tracks/${trackId}/controller`,
    ROUND_CONTROLLER: (roundId) => `/api/v1/presentation/rounds/${roundId}/controller`,
    CONTROLLER_HEARTBEAT: '/api/v1/presentation/controller/heartbeat',
    QUEUE_SKIP: '/api/v1/presentation/queue/skip',
  },
  NOTIFICATIONS: {
    ME: '/api/v1/me/notifications',
    MARK_READ: '/api/v1/me/notifications/read',
  },
};