export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/signup',
    APPROVE: (userId) => `/api/auth/approve/${userId}`,
    TEMP_JUDGE: '/api/auth/judge/temp',
    OAUTH_GOOGLE_LOGIN: '/api/auth/oauth/google',
    OAUTH_GITHUB_LOGIN: '/api/auth/oauth/github',
    OAUTH_GOOGLE_LINK: '/api/auth/oauth/google/link',
    OAUTH_GOOGLE_UNLINK: '/api/auth/oauth/google/unlink',
    OAUTH_GITHUB_LINK: '/api/auth/oauth/github/link',
    OAUTH_GITHUB_UNLINK: '/api/auth/oauth/github/unlink',
  },
  HACKATHONS: {
    BASE: '/api/hackathons',
    DETAIL: (id) => `/api/hackathons/${id}`,
    ONGOING: (id) => `/api/hackathons/${id}/ongoing`,
    ROUNDS: (hackathonId) => `/api/hackathons/${hackathonId}/rounds`,
    EVENTS: (hackathonId) => `/api/hackathons/${hackathonId}/events`,
    LOTTERY: (hackathonId) => `/api/hackathons/${hackathonId}/lottery`,
    PRIZES: (hackathonId) => `/api/hackathons/${hackathonId}/prizes`,
    FINISH: (hackathonId) => `/api/hackathons/${hackathonId}/finish`,
    EXPORT_RBL: (hackathonId) => `/api/hackathons/${hackathonId}/export-rbl`,
    TEAMS_LOCK: (hackathonId) => `/api/hackathons/${hackathonId}/teams/lock`,
    TRACKS: (hackathonId) => `/api/hackathons/${hackathonId}/tracks`,
    STATUS: (hackathonId) => `/api/hackathons/${hackathonId}/status`,
    READINESS: (hackathonId) => `/api/hackathons/${hackathonId}/readiness`,
  },
  ROUNDS: {
    DETAIL: (roundId) => `/api/rounds/${roundId}`,
    TRACKS: (roundId) => `/api/rounds/${roundId}/tracks`,
    LOCK: (roundId) => `/api/rounds/${roundId}/lock`,
    VARIANCE: (roundId) => `/api/rounds/${roundId}/variance`,
    PROGRESS: (roundId) => `/api/rounds/${roundId}/progress`,
    TRANSITION_DETAILS: (roundId) => `/api/rounds/${roundId}/transition-details`,
    TRANSITION: (roundId) => `/api/rounds/${roundId}/transition`,
    ACTIVATE: (roundId) => `/api/rounds/${roundId}/activate`,
    CRITERIA: (roundId) => `/api/rounds/${roundId}/criteria`,
    CRITERIA_CLONE: (roundId) => `/api/rounds/${roundId}/criteria/clone`,
  },
  TRACKS: {
    DETAIL: (trackId) => `/api/tracks/${trackId}`,
    CRITERIA: (trackId) => `/api/tracks/${trackId}/criteria`,
    CRITERIA_CLONE: (trackId) => `/api/tracks/${trackId}/criteria/clone`,
    CRITERIA_CLONE_SOURCES: (trackId) => `/api/tracks/${trackId}/criteria/clone-sources`,
  },
  CRITERIA: {
    BASE: '/api/criteria',
    DETAIL: (id) => `/api/criteria/${id}`,
  },
  TEAMS: {
    BASE: '/api/teams',
    DETAIL: (teamId) => `/api/teams/${teamId}`,
    INVITE: (teamId) => `/api/teams/${teamId}/invite`,
    INVITE_MEMBER: (teamId) => `/api/teams/${teamId}/invite`,
    RESPOND: (teamId) => `/api/teams/${teamId}/respond`,
    APPROVE: (teamId) => `/api/teams/${teamId}/approve`,
    MEMBER_DETAIL: (teamId, userId) => `/api/teams/${teamId}/members/${userId}`,
    TRANSFER_LEADER: (teamId) => `/api/teams/${teamId}/leader`,
    UPDATE_TRACK: (teamId, roundId) => `/api/teams/${teamId}/rounds/${roundId}/track`,
    MENTOR: (teamId, roundId) => `/api/teams/${teamId}/rounds/${roundId}/mentor`,
  },
  SCORES: {
    BASE: '/api/scores',
  },
  SUBMISSIONS: {
    BASE: '/api/submissions',
    REVIEW: (id) => `/api/submissions/${id}/review`,
  },
  EVENTS: {
    DETAIL: (id) => `/api/events/${id}`,
  },
  USERS: {
    ME: '/api/users/me',
    ME_STUDENT_CARD: '/api/users/me/student-card',
    STATUS: (userId) => `/api/users/${userId}/status`,
    LIST: '/api/users',
    DETAIL: (userId) => `/api/users/${userId}`,
    TEMP_JUDGES: '/api/users/temp-judges',
    RESEND_INVITATION: (invitationId) => `/api/invitations/${invitationId}/resend`,
  },
};